services:
  - type: web
    name: bughunters-api
    env: docker
    dockerContext: Backend
    dockerfilePath: Backend/Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
